# Generated by Django 6.0.1 on 2026-02-01 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('csv_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reply_to', models.EmailField(blank=True, max_length=255, null=True)),
                ('batch_size', models.IntegerField(default=50)),
                ('delay_between_batches', models.FloatField(default=1.0)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enable_open_tracking', models.BooleanField(default=True)),
                ('enable_click_tracking', models.BooleanField(default=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('brevo_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='verifier.emailcampaign')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='verifier.campaignrecipient')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='verifier.emailcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('disposable_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('disposable', 'Disposable'), ('risky', 'Risky'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('syntax_valid', models.BooleanField(default=False)),
                ('domain_exists', models.BooleanField(default=False)),
                ('mx_records_found', models.BooleanField(default=False)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_role_account', models.BooleanField(default=False)),
                ('is_free_email', models.BooleanField(default=False)),
                ('has_dns_security', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('mx_records', models.JSONField(blank=True, default=list)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('normalized_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='verifier.verificationjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['user', 'created_at'], name='verifier_em_user_id_30ae01_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', 'created_at'], name='verifier_em_status_7a5c98_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='verifier_ca_campaig_c0981b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['email'], name='verifier_ca_email_ac303a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'email')},
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['campaign', 'level'], name='verifier_ca_campaig_86fbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationjob',
            index=models.Index(fields=['status', 'created_at'], name='verifier_ve_status_9aa59a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationjob',
            index=models.Index(fields=['user', 'created_at'], name='verifier_ve_user_id_0a8c10_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresult',
            index=models.Index(fields=['job', 'status'], name='verifier_em_job_id_1419f7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresult',
            index=models.Index(fields=['email'], name='verifier_em_email_7420d2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresult',
            index=models.Index(fields=['status'], name='verifier_em_status_ae8283_idx'),
        ),
    ]
