# Generated by Django 6.0.1 on 2026-01-27 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposableEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('risky', 'Risky'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('syntax_valid', models.BooleanField(default=False)),
                ('domain_exists', models.BooleanField(default=False)),
                ('mx_records_found', models.BooleanField(default=False)),
                ('smtp_valid', models.BooleanField(default=False)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('mx_records', models.JSONField(blank=True, default=list)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('normalized_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verification_time_ms', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='verifier.verificationjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationjob',
            index=models.Index(fields=['status', 'created_at'], name='verifier_ve_status_9aa59a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationjob',
            index=models.Index(fields=['user', 'created_at'], name='verifier_ve_user_id_0a8c10_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresult',
            index=models.Index(fields=['job', 'status'], name='verifier_em_job_id_1419f7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresult',
            index=models.Index(fields=['email'], name='verifier_em_email_7420d2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresult',
            index=models.Index(fields=['status'], name='verifier_em_status_ae8283_idx'),
        ),
    ]
