# Generated by Django on 2026-01-28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationjob',
            name='disposable_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailresult',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('disposable', 'Disposable'), ('risky', 'Risky'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.RemoveField(
            model_name='emailresult',
            name='smtp_valid',
        ),
        migrations.RemoveField(
            model_name='emailresult',
            name='is_catch_all',
        ),
        migrations.RemoveField(
            model_name='emailresult',
            name='verification_time_ms',
        ),
    ]
