# Generated by Django 6.0.1 on 2026-01-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationjob',
            name='disposable_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailresult',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('disposable', 'Disposable'), ('risky', 'Risky'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
