# Generated by Django 6.0.1 on 2026-01-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_verificationjob_disposable_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailresult',
            name='is_catch_all',
        ),
        migrations.RemoveField(
            model_name='emailresult',
            name='smtp_valid',
        ),
        migrations.RemoveField(
            model_name='emailresult',
            name='verification_time_ms',
        ),
        migrations.AddField(
            model_name='emailresult',
            name='has_dns_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailresult',
            name='is_free_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailresult',
            name='is_role_account',
            field=models.BooleanField(default=False),
        ),
    ]
